“name: Welcome New Contributor 
 
on: 
pull_request_target: 
types: [opened] 
 
jobs: greet: 
runs-on: ubuntu-latest steps: 
-	name: Welcome Message uses: actions/first-interaction@v1 with: 
repo-token: ${{ secrets.GITHUB_TOKEN }} 
issue-message: | 艓艔艕艖艗艘 #Welcome to the SCM Practical Repository!# 
 
Hey there, and welcome aboard! This repository is part of our Source Code Management (SCM) practical tasks, where we explore Git, GitHub, and automation with GitHub Actions. 
 
Here’s a quick intro: 
-	궚궛궜궝궞궟궠궡궖궙궗궘 Purpose: Learn and demonstrate SCM concepts through hands-on activities like branching, merging, and automation. 
-	뭄뭆뭅뭃 Folder Structure: You'll find experiment-specific files organized by tasks (e.g., `experiment-1`, `experiment-8`, etc.). 
-	밴밵밶밷밸밹밻밼배백밲밳밺 Collaborate: Got questions or suggestions? Feel free to open issues or discussions! 
 
We’re super excited to have you contributing—let’s make learning Git & GitHub fun together! 곻과곽곸곹곺 
 
pr-message: | 뜡뜢뜞뜟뜠뜜뜝 Thanks for your first pull request to the SCM Practical Repository! 
 
We appreciate your contribution to this educational repo focused on Git and GitHub workflows. 
-	We’ll review your changes shortly. 
-	Be sure to follow any experiment-specific formats or file naming conventions. 
 
Welcome to the team of contributors! 蔿蕁蕀蕂蕃蕄蕇蕈蕉蕊蕅蕆蕋 Keep learning, keep coding!” 
